# Generated by Django 4.1.4 on 2022-12-20 08:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("date_to_start", models.DateField()),
                ("start_time", models.TimeField()),
                ("finish_time", models.TimeField()),
                ("street_address", models.CharField(max_length=50)),
                (
                    "fax_number",
                    phone_field.models.PhoneField(max_length=31, unique=True),
                ),
                (
                    "phone_number",
                    phone_field.models.PhoneField(max_length=31, unique=True),
                ),
                ("department_Location", models.CharField(max_length=50)),
                ("project_name", models.CharField(max_length=250)),
                ("company_address", models.CharField(max_length=50)),
            ],
            options={"verbose_name_plural": "Events",},
        ),
    ]
